project:
  type: book
  output-dir: docs

book:
  title: "Computer Science 1"
  author:
  - name: Kálmán Abari
    email: abari.kalman@arts.unideb.hu
    affiliations:
      - name: Univeristy of Debrecen, Institute of Psychology
        address: "Egyetem tér 1."
        city: Debrecen
        postal-code: 4032
  doi: "BTPS1210BA-E"
  date: today
  chapters:
    - index.qmd
    - syllabus.qmd
    - details.qmd
    - software.qmd
    # - terms.qmd
    - academic_calendar.qmd
    #- learning_objectives.qmd
    - references.qmd

  cover-image: cover.jpg
  search: true

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

author-title: Instructor
doi-title: "Course Number"
csl: apa.csl

