---
bibliography: references.bib
---

# Syllabus

**Course Number**: BTPS1210BA-E\
**Credits**: 2\
**Course type**: Practical\
**Year**: 2024/25/1, Semester 1 (Autumn)\
**Class Location**: P/106/A, Institute of Psychology, University of Debrecen\
**Meeting Times**: Tuesday 10:00 - 11:40\
**Contact Information**: Please contact me through email anytime: [abari.kalman\@arts.unideb.hu](mailto:abari.kalman@arts.unideb.hu){.email}

## Course overview

During the course, students will acquire the basic digital skills they will need for their studies. The course attempts to balance the knowledge levels of students with different backgrounds. At the beginning of the course, students will learn basic methods of word processing, spreadsheet and presentation design.

The main purpose of the course is to support statistics courses. Today, statistical analysis is carried out by computer, so knowledge of one (or more) statistical software packages is essential. The rest of the course, students will be introduced to the *jamovi* statistical software and will also be introduced to the use of *R/RStudio*. The *jamovi* part of the course will cover statistical processes of data entry and data preparation, descriptive analysis, and graphic analysis. In *RStudio* students will be able to create markdown-based documents and generate HTML documents.

## Attendance

Active participation is an important part of this class. Attendance are required. The maximum number of absences from the practical sessions is three. If the student exceeds the maximum number of absences, a practical grade will not be given and a "refused" will be entered in the electronic learning system.

## Assessment and Grades {#assessment}

During the semester there will be 4 homework assignments and one project. Extra points can be earned by working in class, presenting a Kahoot! test or winning a Kahoot! test (3 points each).

+---------------------------------+------------+-------------------------------------------------------------------+-----------------------------------+
| Components                      | Points     | Links                                                             | Dates                             |
+=================================+============+===================================================================+===================================+
| **Homework 1**                  | 15         | [Details](homework/homework_1.html){target="_blank"}[^syllabus-1] | October 15.                       |
|                                 |            |                                                                   |                                   |
| -   RStudio reporting: markdown |            |                                                                   |                                   |
|                                 |            |                                                                   |                                   |
| -   Quarto document             |            |                                                                   |                                   |
+---------------------------------+------------+-------------------------------------------------------------------+-----------------------------------+
| **Homework 2**                  | 15         | [Details](homework/homework_2.html){target="_blank"}[^syllabus-2] | November 5.                       |
|                                 |            |                                                                   |                                   |
| -   Jamovi (1)                  |            |                                                                   |                                   |
|                                 |            |                                                                   |                                   |
| -   JabRef                      |            |                                                                   |                                   |
+---------------------------------+------------+-------------------------------------------------------------------+-----------------------------------+
| **Homework 3**                  | 15         | [Details](homework/homework_3.html){target="_blank"}[^syllabus-3] | November 26.                      |
|                                 |            |                                                                   |                                   |
| -   Jamovi (2)                  |            |                                                                   |                                   |
+---------------------------------+------------+-------------------------------------------------------------------+-----------------------------------+
| **Homework 4**                  | 15         | [Details](homework/homework_4.html){target="_blank"}[^syllabus-4] | December 10.                      |
|                                 |            |                                                                   |                                   |
| -   Word                        |            |                                                                   |                                   |
|                                 |            |                                                                   |                                   |
| -   JabRef                      |            |                                                                   |                                   |
+---------------------------------+------------+-------------------------------------------------------------------+-----------------------------------+
| **Project final artifact**      | 30         | [Details](homework/pfa.html){target="_blank"}[^syllabus-5]        | November 10. and December 6.      |
+---------------------------------+------------+-------------------------------------------------------------------+-----------------------------------+
| **Project final presentation**  | 10         | [Details](homework/pfp.html){target="_blank"}                     | December 10. 12:00-15:30, P/106/A |
+---------------------------------+------------+-------------------------------------------------------------------+-----------------------------------+
| **TOTAL**                       | 100        |                                                                   |                                   |
+---------------------------------+------------+-------------------------------------------------------------------+-----------------------------------+

: Points and deadlines {.striped .hover .w-auto .mx-auto}

[^syllabus-1]: Hint: [My solution of Homework 1](homework/homework_1_example.html)

[^syllabus-2]: Hint: [My solution of Homework 2](homework/homework_2_example.html)

[^syllabus-3]: Hint: [My solution of Homework 3](homework/homework_3_example.html)

[^syllabus-4]: Hint: [My solution of Homework 4](homework/homework_4_example.docx)

[^syllabus-5]: Hint: [My solution of Project final artifact](homework/pfa_XYZ123_example.html). [My solution of The answer](homework/pfa_XYZ123_example.pptx).

| Points | Grade offered |
|--------|---------------|
| 0--50  | 1 (failed)    |
| 51--60 | 2             |
| 61--74 | 3             |
| 75--85 | 4             |
| 86--   | 5             |

: Grading {.striped .hover .w-auto .mx-auto}

## Course details

+-------------+----------------------------------------------+-------------------------------+
| Day         | Topic                                        | Links                         |
+=============+==============================================+===============================+
| Sept 10     | Intro                                        | [Details](details.qmd#sec-01) |
+-------------+----------------------------------------------+-------------------------------+
| Sept 17     | Files, directories, compressing              | [Details](details.qmd#sec-02) |
+-------------+----------------------------------------------+-------------------------------+
| Sept 24     | RStudio reporting: markdown, Quarto document | [Details](details.qmd#sec-03) |
+-------------+----------------------------------------------+-------------------------------+
| Oct 1       | JabRef - Bibliography management             | [Details](details.qmd#sec-04) |
+-------------+----------------------------------------------+-------------------------------+
| Oct 8       | TXT, CSV, Spreadsheets                       | [Details](details.qmd#sec-05) |
+-------------+----------------------------------------------+-------------------------------+
| Oct 15      | Jamovi - Introduction                        | [Details](details.qmd#sec-06) |
+-------------+----------------------------------------------+-------------------------------+
| Oct 22      | Autumn break                                 |                               |
+-------------+----------------------------------------------+-------------------------------+
| Oct 29      | Jamovi - Import data, Data conversion        | [Details](details.qmd#sec-07) |
+-------------+----------------------------------------------+-------------------------------+
| Nov 5       | Jamovi - Data transformation                 | [Details](details.qmd#sec-08) |
+-------------+----------------------------------------------+-------------------------------+
| Nov 12      | Jamovi - Descriptive statistics I.           | [Details](details.qmd#sec-09) |
+-------------+----------------------------------------------+-------------------------------+
| Nov 19      | Jamovi - Descriptive statistics II.          | [Details](details.qmd#sec-10) |
+-------------+----------------------------------------------+-------------------------------+
| Nov 26      | Word - Styles, TOC, Bibliography, APA7       | [Details](details.qmd#sec-11) |
+-------------+----------------------------------------------+-------------------------------+
| Dec 3       | Presentation: Power Point                    | [Details](details.qmd#sec-12) |
+-------------+----------------------------------------------+-------------------------------+
| Dec 10      | Project presentation                         | [Details](details.qmd#sec-13) |
+-------------+----------------------------------------------+-------------------------------+

: Course details {.striped .hover .w-auto .mx-auto}

## Textbooks

-   **Required:**
    -   @uoh2023 [1 Introduction, Advanced studies: presenting data]
    -   @Navarro2018 [1-117]
    -   @Poulson2019 [Getting started, Wrangling data, Exploration]
-   **Optional texts:**
    -   @pajankar2022
    -   @Cote2021 [1-77]
    -   @Sarty2023 [1-109]
    -   @datascience_tntlab_org

## Software

The course requires some [software](software.qmd).

## Prerequisites

No prerequisite is required. Prior knowledge in computer literacy (word processing, spreadsheets, presentation) is recommended but not required.
